apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  namespace: azurefactory
  name: azurefactory-web
  description: Web collection for AzureFactory
spec:
  owner: azurefactory/unicorns
  domain: azurefactory
