apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  namespace: azurefactory
  name: azurefactory-web
  description: Web collection for AzureFactory
spec:
  owner: azurefactory/unicorns
  domain: default/azurefactory
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: create_web_app_002
  namespace: azurefactory-web
  description: Create Azure WebApp role
  tags:
    - azurefactory
    - web
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
spec:
  type: library
  lifecycle: production
  owner: azurefactory/azurefactory-web-team
  system: azurefactory/azurefactory-web
  dependsOn: ['component:azurefactory-networking/create_private_link_001', 'resource:azure/private-link', 'resource:azure/azure-web-app']
