apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  namespace: azurefactory
  name: azurefactory-networking
  description: Networking collection for AzureFactory
spec:
  owner: azurefactory/unicorns
  domain: azurefactory
