apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  namespace: azurefactory
  name: azurefactory-security
  description: Security collection for AzureFactory
spec:
  owner: azurefactory/unicorns
  domain: default/azurefactory
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: azurefactory-security
  name: login_vault_001
  description: Login to EVA vault role
  tags:
    - azurefactory
    - security
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
spec:
  type: library
  lifecycle: production
  owner: azurefactory/unicorns
  system: azurefactory/azurefactory-security
