apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.swci | dump }}
spec:
  type: service
  owner: user:azurefactory/trzecimi
  lifecycle: experimental
  dependsOn: [
    'component:azurefactory-web/create_web_app_002',
    'component:azurefactory-networking/create_private_endpoint_001', 
    'component:azurefactory-core/check_azcli_001',
    'component:azurefactory-core/create_resource_group_001',
    'component:azurefactory-security/set_subscription_001',
  ]