apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: azurefactory-networking
  name: create_private_link_001
  description: Create Azure Private Link role
  tags:
    - azurefactory
    - networking
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
spec:
  type: library
  lifecycle: production
  owner: azurefactory/unicorns
  system: azurefactory-networking
  dependsOn: ['resource:azure/private-link']
